/*
//Tang, Chen
//Jan 17 2019
 * Do Survey form
 * 
 */
package finalproject.tang.chen;

import java.awt.Color;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

public class DoSurvey extends javax.swing.JFrame {

    Welcome firstWindow;
    ChoiceDoSurvey choiceDoSurvey;

    /**
     * Creates the DoSurvey form
     *
     * @param m - the parent form (main menu)
     */
    public DoSurvey(Welcome m) {
        initComponents();
        firstWindow = m;
        getContentPane().setBackground(new Color(153, 204, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCreated = new javax.swing.JButton();
        btnGoogle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Do The Survey");

        btnBack.setBackground(new java.awt.Color(255, 212, 26));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Which type of survey would you like to do?");

        btnCreated.setBackground(new java.awt.Color(255, 212, 26));
        btnCreated.setText("Created Survey");
        btnCreated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatedActionPerformed(evt);
            }
        });

        btnGoogle.setBackground(new java.awt.Color(255, 212, 26));
        btnGoogle.setText("Google Forms");
        btnGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoogleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnCreated))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGoogle)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnBack)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(btnCreated)
                .addGap(41, 41, 41)
                .addComponent(btnGoogle)
                .addGap(42, 42, 42)
                .addComponent(btnBack)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When the "Back" button is pressed
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //change visibility to go back to the main menu
        firstWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * When the "Create Survey" button is selected
     */
    private void btnCreatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatedActionPerformed
        //If no ChoiceDoSurvey form exists, create a new one
        if (choiceDoSurvey == null) {
            choiceDoSurvey = new ChoiceDoSurvey(this);
        }
        
        //Change visiblity of forms to link to the next form respective to the user's choice
        choiceDoSurvey.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCreatedActionPerformed

    /**
     * When the "Google Forms" button is pressed
     */
    private void btnGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoogleActionPerformed
        //Prompt the user before going to google
        JOptionPane.showMessageDialog(null, "We are going to take you to Google,\n where you will enter the URL of the survey provided by the person asking you to take the survey");
        
        try {
            //Go to google
            java.awt.Desktop.getDesktop().browse(new URI("https://www.google.ca"));
        
        } catch (IOException e) {
            JOptionPane.showInputDialog(null, "ERROR: " + e);
        } catch (URISyntaxException e) {
            JOptionPane.showInputDialog(null, "ERROR: " + e);
        }
        
        //change visibility to go back to main menu
        firstWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGoogleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreated;
    private javax.swing.JButton btnGoogle;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
