/*
//Tang, Chen
//Jan 17 2019
 * SelectSurvey form
 * This form is opened after the user chooses to create a survey in java from the ChoiceOfSurvey form.
 * The user can choose to make a new survey, or continue to modify a created survey.
 * They can also go back to the ChoiceOfSurvey menu with the "Back" button.
 */
package finalproject.tang.chen;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class SelectSurvey extends javax.swing.JFrame {

    ChoiceOfSurvey choice;
    MakeSurvey makeSurvey;

    /**
     * This is the primary constructor of the SelectSurvey form
     *
     * @param choice - The user's chosen choice of survey creation
     */
    public SelectSurvey(ChoiceOfSurvey choice) {
        initComponents();
        this.choice = choice;
        getContentPane().setBackground(new Color(153, 204, 255));
        setExistingSurvey();
    }

    /**
     * This method will read the existing surveys from a file, and then load the
     * survey names into the combo box that shows the names of the surveys
     */
    public void setExistingSurvey() {
        try {
            //Set reader to the file containing all the names of the surveys
            FileReader fr = new FileReader("src\\finalproject\\tang\\chen\\SurveyStorage");
            BufferedReader br = new BufferedReader(fr);

            String title;
            boolean eof = false;

            //Read each line of the file until there are no more survey names contained
            while (!eof) {
                
                //Read the line and get the name of the survey
                title = br.readLine();

                //If the name of the survey is not an empty line, add the name to the combo box displaying the surveys
                if (title == null) {
                    
                    //If an empty line is read, the end of the file and reached, and the program can stop reading
                    eof = true;
                    
                } else {
                    
                    //Add the name of the survey to the combo box
                    cboSurveys.addItem(title);
                }
            }
            br.close();
        } catch (IOException e) {
            System.out.println("ERROR " + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExisting = new javax.swing.JButton();
        cboSurveys = new javax.swing.JComboBox();
        btnNew = new javax.swing.JButton();
        lblQuestion = new javax.swing.JLabel();
        lblExisting = new javax.swing.JLabel();
        lblNew = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExisting.setBackground(new java.awt.Color(255, 212, 26));
        btnExisting.setText("GO!");
        btnExisting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistingActionPerformed(evt);
            }
        });

        btnNew.setBackground(new java.awt.Color(255, 212, 26));
        btnNew.setText("NEW!");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        lblQuestion.setText("Which Survey Are You Working On?");

        lblExisting.setText("Existing Survey");

        lblNew.setText("New Survey");

        btnBack.setBackground(new java.awt.Color(255, 212, 26));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExisting)
                            .addComponent(lblNew))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNew)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboSurveys, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExisting))))
                    .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblQuestion)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExisting)
                    .addComponent(cboSurveys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExisting))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(lblNew))
                .addGap(46, 46, 46)
                .addComponent(btnBack)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When the button to go back to the ChoiceOfSurvey menu - "Back" - is
     * selected
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //Change visiblity of forms to link to the next form respective to the user's choice
        choice.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * When the button to make a new survey - "NEW!" - is selected
     */
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        //If no MakeSurvey exists, create a new one
        if (makeSurvey == null) {
            makeSurvey = new MakeSurvey(this);
        }

        //Change visiblity of forms to link to the next form respective to the user's choice
        makeSurvey.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNewActionPerformed

    /**
     * When the button to continue working on a survey - "GO!" - is selected
     */
    private void btnExistingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistingActionPerformed
        //If no MakeSurvey exists, create a new one
        if (makeSurvey == null) {
            //Passes chosen survey from combo box into MakeSurvey constructor
            makeSurvey = new MakeSurvey(this, cboSurveys.getSelectedItem().toString());
        }

        //Change visiblity of forms to link to the next form respective to the user's choice
        makeSurvey.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExistingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExisting;
    private javax.swing.JButton btnNew;
    private javax.swing.JComboBox cboSurveys;
    private javax.swing.JLabel lblExisting;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables
}
